apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end

spec:
  template:
    metadata:
      name: nginx
      labels:
        type: front-end
        app: nginx
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:latest
  replicas: 11
  selector:
    matchLabels:
      type: front-end
