apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end

spec:
  template:
    metadata:
      name: nginx
      labels:
        type: server
        app: nginx
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:latest
  replicas: 10
